### ISSUE TITLE
리뷰 목록 박스 공통 컴포넌트

### ISSUE THREAD

**Issue by myoungsuboh** [myoungsuboh/wine#7]
[Issue]---------------------------------

## ✏️ Description
- 리뷰 목록 박스 공통 컴포넌트 구현
## 📋 TODO
- [ ] 할 일 : material ui 사용
- [ ] 할 일 : 공통으로 사용하는거니 순수 모달 기능만 동작하도록
- [ ] 할 일 : 우측 상단에 상세 보기 기능이 필요함.

## ⏱️ 예상 소요 시간
- 3시간

## 💬 추가 설명
https://www.notion.so/WINE-15935138cc9a8069b008f8e1c6cf3679?p=15b35138cc9a801fab7ae1539fef62cd&pm=s
